import type { ContestDetail } from "../_types";

export const MOCK_CONTESTS: ContestDetail[] = [
  {
    id: "travel-innovation-idea",
    title: "2026트래블이노베이션 아이디어 공모전",
    organizer: "야놀자레저, 놀유니버스",
    category: "기획/아이디어",
    dDay: "D-26",
    viewCount: 211,
    posterImageUrl: "",
    isScrapped: false,
    applicationPeriod: "06.29 - 07.09",
    eligibility: "대학생",
    prize: "총 10개 작품\n- 대상 1명",
    description: "지역축제 활성화를 위한 기획 및 전략방안지\n역축제 활성화를 위한 기획 및 전략방안지역\n축제 활성화를 위한 기획 및 전략방안",
    websiteUrl: "https://www.yanolja-research.com",
  },
  {
    id: "chai-ai-ad",
    title: "2026 CHAI 대학생 AI 광고 공모전",
    organizer: "차이커뮤니케이션",
    category: "기획/아이디어",
    dDay: "D-37",
    viewCount: 1984,
    posterImageUrl: "",
    isScrapped: true,
    applicationPeriod: "06.29 - 07.09",
    eligibility: "대학생",
    prize: "총 10개 작품",
    description: "",
    websiteUrl: "",
  },
  {
    id: "codegate-ai-startup",
    title: "2026 코드게이트 AI 스타트업 해커톤",
    organizer: "(주)한컴이노스트림",
    category: "IT/AI/기술",
    dDay: "D-15",
    viewCount: 3994,
    posterImageUrl: "",
    isScrapped: true,
    applicationPeriod: "05.21 - 07.08",
    eligibility: "AI 서비스 개발에 관심 있는 누구나",
    prize: "총 10개 팀",
    description: "",
    websiteUrl: "",
  },
  {
    id: "seoul-innovation-idea",
    title: "2026년 혁신 아이디어 공모전",
    organizer: "서울특별시농수산식품공사",
    category: "기획/아이디어",
    dDay: "D-22",
    viewCount: 2603,
    posterImageUrl: "",
    isScrapped: false,
    applicationPeriod: "06.10 - 07.15",
    eligibility: "전 국민",
    prize: "총 8개 작품",
    description: "",
    websiteUrl: "",
  },
];
